### ISSUE TITLE
Do you have code for Lambda Forward instead Redirect

### ISSUE THREAD

**Issue by vipulkaneriya** [ModusCreateOrg/lambda-redirector#15]
In Redirect my url get change to new domain which is expected. do you have code where i can use my same url and get content from new domain? I am looking for HTTP REVERSE PROXY kind of Lambda based solution

**Comment by obscurerichard** [comment]
Sorry, that is out of scope for this project. You are welcome to adapt this code as it is under a permissive MIT license, however.
